name: k8s execution tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/kfp-kubernetes-execution-tests.yml'
      - '.github/resources/**'
      - 'sdk/python/**'
      - 'api/v2alpha1/**'
      - 'kubernetes_platform/**'

jobs:
  kfp-kubernetes-execution-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        k8s_version: [ "v1.29.2", "v1.30.2", "v1.31.0" ]
    name: kfp-kubernetes execution tests - K8s ${{ matrix.k8s_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create KFP cluster
        uses: ./.github/actions/kfp-cluster
        with:
          k8s_version: ${{ matrix.k8s_version }}

      - name: Install requirements 
        run: make setup-kfp-kubernetes-execution-tests-without-kfp

      - name: Forward port and run tests
        run: make test-kfp-kubernetes-execution-tests
