name: KFP SDK execution tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/sdk-execution.yml'
      - '.github/resources/**'
      - 'sdk/python/**'
      - 'api/v2alpha1/**'
      - 'backend/src/v2/compiler/**'

jobs:
  sdk-execution-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        k8s_version: [ "v1.29.2", "v1.30.2", "v1.31.0" ]
    name: KFP SDK Execution Tests - K8s ${{ matrix.k8s_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create KFP cluster
        uses: ./.github/actions/kfp-cluster
        with:
          k8s_version: ${{ matrix.k8s_version }}

      - name: Install requirements
        run: make setup-sdk-execution

        # Same as sdk-component requirements
      - name: Forward API port and run tests
        id: tests
        run: |
          make test-sdk-execution
        continue-on-error: true

      - name: Collect failed logs
        if: steps.tests.outcome != 'success'
        run: |
          ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
          exit 1

      - name: Collect test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: periodic-functional-artifacts-k8s-${{ matrix.k8s_version }}
          path: /tmp/tmp*/*
